name: Build & Push Docker Image

on:
  push:
    branches:
      - "main"
  # https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
  workflow_dispatch: {}

jobs:
  docker:
    runs-on: ubuntu-24.04-arm
    steps:
      # No checkout step here because build-push-action uses git context by default:
      # https://github.com/marketplace/actions/build-and-push-docker-images#git-context
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: true
          tags: "{{username}}/{{project-name}}:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
